### ISSUE TITLE
Link in HA log to issues is not working, directs to https://github.com/briis/affald/issues

### ISSUE THREAD

**Issue by ZenithDK** [briis/affalddk#10]
### Describe the issue

The correct URL is https://github.com/briis/affalddk/issues

### What version of Home Assistant Core has the issue?

core-2024.2.5

### What was the last working version of Home Assistant Core?

core-2024.2.5

### What type of installation are you running?

Home Assistant Supervised

### Diagnostics information

Not relevant

**Comment by briis** [comment]
Bummer... Tak for det, den var lige smuttet. 👍
Det er rettet, og kommer med i næste release.
