### ISSUE TITLE
favrskov Municipalities

### ISSUE THREAD

**Issue by andreasjuhl2000** [briis/affalddk#103]
### Describe the feature you wish to make a request for

favrskov Municipalities is a member of affald.dk please add support for favrskov

**Comment by briis** [comment]
Jeg får undersøgt udbyderen og ser om jeg kan finde en måde at trække data ud på.

**Comment by briis** [comment]
Tjekkede lige adbad.dk og den adresse virker ikke. Har du flere informationer?

**Comment by andreasjuhl2000** [comment]
Hej,Jeg kan se via affald.dk at favrskov kommunen skulle være medlem, så jeg gik ud fra det skulle virke. Hvad mangler du for at vi kan komme videre?lær om affald, genbrug og miljøaffald.dkSendt fra min iPhoneDen 13. jun. 2024 kl. 09.11 skrev Bjarne Riis ***@***.***>:﻿
Tjekkede lige adbad.dk og den adresse virker ikke. Har du flere informationer?

**Comment by andreasjuhl2000** [comment]
Hej,Her er favrskov kommunen hjemme, hvor man kan se tømme dage, kan du bruge denne?Se, hvornår vi henter affald på din adresse.favrskovforsyning.dkSendt fra min iPhoneDen 13. jun. 2024 kl. 11.17 skrev Andreas Juhl ***@***.***>:﻿Hej,Jeg kan se via affald.dk at favrskov kommunen skulle være medlem, så jeg gik ud fra det skulle virke. Hvad mangler du for at vi kan komme videre?lær om affald, genbrug og miljøaffald.dk<apple-touch-icon.png>Sendt fra min iPhoneDen 13. jun. 2024 kl. 09.11 skrev Bjarne Riis ***@***.***>:﻿
Tjekkede lige adbad.dk og den adresse virker ikke. Har du flere informationer?

**Comment by andreasjuhl2000** [comment]
Hej, 
er i kommet længere med favrskov? de er medlem af affald.dk. 
https://www.favrskovforsyning.dk/se-dine-toemningsdage
på forhånd tak

**Comment by briis** [comment]
Jeg har kigget lidt på affalf.dk, men den måde de leverer data på er ikke så nemt at trække data fra, da jeg ikke lige har fundet en metode til at kun at få rå data, men kun en færdig html side, og det kan jeg ikke arbejde videre med.
Så tidshorisonten, hvis det er muligt, er ukendt.

**Comment by andreasjuhl2000** [comment]
okay tusind tak for forsøget :) man kan ikke bruge favrskov egen hjemmeside? kan se opbygning minder lidt om opsætning af jeres modul, med adresse obs.

**Comment by briis** [comment]
I princippet jo, men det vil betyde man skal lave det man kalder Web Scraping, altså lede efter bestemte ord eller karakterer i html koden, og så trække de nødvendige data derfra. Problemet opstår i samme øjeblik de så flytter lidt rundt på teksten, så virker det ikke mere.
Samtidig, så har de andre kommuner der anvender affald.dk måske et lidt andet layout, og man skal så reelt lave noget individuelt for hver eneste kommune. Det hverken kan eller vil jeg vedligeholde.

Så jeg bruger aldrig Web Scraping, men det skal jo ikke forhindre dig i at klone min kode og lave de nødvendige tilretninger. 😀

**Comment by andreasjuhl2000** [comment]
kan jeg godt forstå, så det jo også et kæmpe arbejdet, hvor finde du kommuner på affald.dk og tømmedag? jeg kan nemlig se at favrskov fremgår på affald.dk kort over hvilken kommuner der er medlem.

**Comment by briis** [comment]
Jeg var ikke gået i gang med at finde alle kommuner der er tilmeldt endnu, da jeg blot fulgte sporende fra Favrskov, for at se hvilke adresser den hentede data fra og hvordan kaldene til det var. Jeg har ikke givet op endnu, og satser på jeg får lidt mere tid snart til at bruge på dette. Jeg skal nok lade dig vide hvis jeg ikke mener det kan lade sig gøre eller vice versa.

**Comment by andreasjuhl2000** [comment]
igen tusind tak, giver gerne en kop kaffe for støtte dit projekt eller hvordan det normalt virker :)

**Comment by briis** [comment]
Hej igen,
I forbindelse med at jeg har lavet ændringer i mit program så jeg nu kan understøtte nogle kommuner der ikke bruger Renoweb, har jeg kigget på Favrskov igen. De er ikke de eneste der er medlem af Affald.dk og fælles for alle de kommuner er at de ikke leverer data i et data format, men KUN som en website. Og som jeg skrev ovenfor, så er det eneste måde man så kan få data på, at man tager det html kode der laves og søger efter bestemte tekster på siden for så at få nogle data ud. (Web Scraping). Der skal kun rettes en enkelt stavefejl på siden, så kan jeg risikere at skulle opdatere programmet igen, så jeg har valgt ikke at kaste mig over kommuner der ikke leverer data spm data.
Beklager meget, men jeg lukker denne nu.

Jeg har lavet en funktion der gør det muligt at hente data fra en iCalendar fil, så skulle kommunen på et tidspunkt tilbyde I kan abonnere på en sådan en, så åben gerne en ny reuest.
