### ISSUE TITLE
[FR]: Tilføj Bornholm

### ISSUE THREAD

**Issue by been65** [briis/affalddk#114]
### Describe the feature you wish to make a request for

Kan man få Bornholm med på listen, de er på APP'en nu så tænker de bør komme med?

### Describe alternatives you've considered

IAB

### Additional context

IAB

**Comment by briis** [comment]
Jeg har [tidligere undersøgt Bornholm](https://github.com/briis/affalddk/issues/7) og kan desværre ikke hente data ud fra den løsning man bruger nu. Tidligere brugte man Renoweb, men ser ud til at være skiftet til en anden udbyder, som ikke umiddelbart stiller data tilrådighed på en måde der kan bruges her.

**Comment by briis** [comment]
Jeg frigiver snart V2.1.11 som burde understøtte Bornholm. Jeg mangler dog flere test data, så test hvad du får ind, og opret et nyt issue hvis du mangler nogle containere. Husk at inkludere data fra logfilen, da der her står de data jeg skal bruge.
