### ISSUE TITLE
Material type [Genbrugsbeholder, 190 ltr (1 stk.)] is not defined in the system for Genbrug. Please notify the developer. 

### ISSUE THREAD

**Issue by PorreKaj** [briis/affalddk#117]
### Describe the issue

Logger: pyaffalddk.api
Source: custom_components/affalddk/__init__.py:123
integration: Affaldshåndtering DK ([documentation](https://github.com/briis/affalddk), [issues](https://github.com/briis/affalddk/issues))
First occurred: 06:40:38 (3 occurrences)
Last logged: 06:43:47

Material type [Genbrugsbeholder, 190 ltr (1 stk.)] is not defined in the system for Genbrug. Please notify the developer. Municipality: Esbjerg, Address ID: 74742

### What version of Home Assistant Core has the issue?

2024.6.4

### What type of installation are you running?

Home Assistant OS

### What version of the integration are you using?

2.1.10

### Diagnostics information

Logger: pyaffalddk.api
Source: custom_components/affalddk/__init__.py:123
integration: Affaldshåndtering DK ([documentation](https://github.com/briis/affalddk), [issues](https://github.com/briis/affalddk/issues))
First occurred: 06:40:38 (3 occurrences)
Last logged: 06:43:47

Material type [Genbrugsbeholder, 190 ltr (1 stk.)] is not defined in the system for Genbrug. Please notify the developer. Municipality: Esbjerg, Address ID: 74742

**Comment by briis** [comment]
Tak for dette.
Kan du fortælle mig hvad type affald der er i denne? `Genbrugsbeholder, 190 ltr (1 stk.)`

**Comment by PorreKaj** [comment]
Plastik, metal.

Fra appen:
Genbrugsspand
Aflever blød og hård plast, metal og glas i din genbrugsspand.
________________________________

**Comment by briis** [comment]
Tak. Jeg får det fixet.
