### ISSUE TITLE
Konfigurationsflow kunne ikke indlæses

### ISSUE THREAD

**Issue by dkmstdk** [briis/affalddk#13]
### Describe the issue

Jeg får denne fejl når jeg på at konfigurer intergrationen "Konfigurationsflow kunne ikke indlæses: {"message":"Invalid handler specified"

### What version of Home Assistant Core has the issue?

2024.3.0

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

pas

**Comment by briis** [comment]
Samme som #4. Se løsningen deri.
