### ISSUE TITLE
Type mangler for Ringsted

### ISSUE THREAD

**Issue by VagnPetersen** [briis/affalddk#133]
### Describe the issue

Plast og pap mangler hver 2. uge.

### What version of Home Assistant Core has the issue?

core-2024.7.4

### What type of installation are you running?

Home Assistant OS

### What version of the integration are you using?

2.1.13

### Diagnostics information

This error originated from a custom integration.

Logger: pyaffalddk.api
Source: custom_components/affalddk/__init__.py:123
integration: Affaldshåndtering DK (documentation, issues)
First occurred: 11:52:02 (2 occurrences)
Last logged: 11:52:02

Material type [PP/MDK-plast 240 l (hver 2. uge) (1 stk.)] is not defined in the system for Genbrug. Please notify the developer. Municipality: Ringsted, Address ID: 12965
Material type [Metal/glas 240 l (hver 12. uge) (1 stk.)] is not defined in the system for Genbrug. Please notify the developer. Municipality: Ringsted, Address ID: 12965

**Comment by briis** [comment]
Det er fixet. Afventer lige om der kommer flere rettelser, så sender jeg snarest en opdatering.

**Comment by VagnPetersen** [comment]
Super :)
