### ISSUE TITLE
Typer mangler i Solrød

### ISSUE THREAD

**Issue by Lyngtoft** [briis/affalddk#139]
### Describe the issue

Glas og papir, samt miljøkasse mangler i listen.

### What version of Home Assistant Core has the issue?

core-2024.7.3

### What type of installation are you running?

Home Assistant OS

### What version of the integration are you using?

2.1.15

### Diagnostics information

Material type [*240 L 2-delt Papir/glas-dåser en-familie (1 stk.)] is not defined in the system for Genbrug. Please notify the developer. Municipality: Solrød, Address ID: 12028
Material type [*Miljøkasse (1 stk.)] is not defined in the system for Genbrug. Please notify the developer. Municipality: Solrød, Address ID: 12028

**Comment by briis** [comment]
De har lige tilføjet en * i beskrivelsen, men ellers alt som det plejer. Jeg har fixet det og det kommer med i næste release.
