### ISSUE TITLE
[FR]: Embed SVG pictures in integration as `data:base64..` ?

### ISSUE THREAD

**Issue by LordMike** [briis/affalddk#14]
### Describe the feature you wish to make a request for

I read the text on `affalddk_images.zip` and how to serve it from the local webserver - but is this necessary? Both SVG's and PNG's should be embeddable as a data url.

Both the `entity_picture` attribute and the `picture-entity` card use `url` as the reference to the image to show. Url can be a data url, like this:

[example picture-entity card](https://github.com/briis/affalddk/assets/1027111/13042eb9-412d-4321-ae4b-c5b664e303c7)

![image](https://github.com/briis/affalddk/assets/1027111/695c41a9-3bd6-445d-8cd7-b15531e127a3)

### Describe alternatives you've considered

Alternatively host on the internet - but that sucks. :)

### Additional context

SVG as data uri: https://gist.github.com/jennyknuth/222825e315d45a738ed9d6e04c7a88d0

Wikipedia: https://en.wikipedia.org/wiki/Data_URI_scheme#Examples_of_use (example on PNG/SVG/..)

**Comment by LordMike** [comment]
I edited the attribute using the States developer tool, and now have this.

![image](https://github.com/briis/affalddk/assets/1027111/cb7a4fd7-a6b0-4580-87d8-19d3414d9bfd)

![image](https://github.com/briis/affalddk/assets/1027111/00748eec-3dea-4446-86c2-828bdde148d7)

**Comment by LordMike** [comment]
Note, I ran [`svgo`](https://github.com/svg/svgo) ([online edition](https://jakearchibald.github.io/svgomg/)) on the above and reduced the base64 from ~4k to ~700bytes. I can recommend doing that before embedding it as attributes :)

I would've made a PR - but I'm not entirely sure how to, in python, embed the svg files [in the relevant code](https://github.com/briis/affalddk/blob/b30c7f216dab9a13e1d07b9e7510ec675c976d70/custom_components/affalddk/sensor.py#L275) .. :/ I imagine you'll want to read the svg file and then embed it, rather than copy in the base64 into a map.

**Comment by briis** [comment]
Tak Michael,
Jeg ledte faktisk efter en måde at gøre dette på, men kunne ikke lige finde ud af det. Jeg kigger på det og se om jeg ikke kan få det implementeret.
TAK.

**Comment by briis** [comment]
Jeg har nu eksperimenteret med dette og gjort alt hvad jeg kan for at få reduceret størrelsen i de forskellige filer, men nogen af dem kan jeg simpelthen ikke få ned på en størrelse så de ikke overskriver maks længden der er understøtte i HA.
Jeg har prøvet de værktøjer du foreslog og også nogle andre, har du andre ideer til at reducere nogle af de mere komplekse svg filer?

**Comment by LordMike** [comment]
Det ligner, for `images/affalddk/`, at en del af SVG'erne indeholder base64-encoded PNG'er? 

Så er det jo ikke helt rigtigt SVG :). Er det `images/affalddk/` som er filerne der skal bruges? så skal vi nok have fundet nogle SVG'er (og så samtidigt fjerne de artifacts der er i f.eks. `farligtaffald.svg`.

**Comment by briis** [comment]
Du har jo helt ret i at ikke alle filerne er rigtige SVG filer - Jeg kunne ikke finde Haveaffald, Storskrald, Farligtaffald etc, som SVG, kun som PNG, og jeg 'konverterede' dem så til svg.
Hvis du kigger i `images/original` så er det de filer jeg har brugt til at lave de sammensatte svg filer. De orginal kan minimeres til næsten igenting, men så snart jeg sætter 4 af dem sammen, så bliver de store.
Det er nok mine manglende færdigheder omkring grafiske filer.

**Comment by LordMike** [comment]
Jeg har skrevet til Cirkulær (affalds brancheorganisation) da jeg godt kan se der ikke er SVG formater af piktogrammerne på sitet (https://www.affaldspiktogrammer.dk/piktogrammer). Med lidt held har de SVG varianter af dem alle sammen.

Næste bud er Futu, designbureauet der lavede piktogrammerne i første omgang.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by briis** [comment]
Fedt. Tak. Glæder mig til at høre hvad de siger.

**Comment by LordMike** [comment]
Mens vi venter så hentede jeg alle piktogrammerne og kørte dem gennem CloudConvert. Det gav et rimeligt godt resultat - de fleste er få KB store, mens enkelte rammer 20 KB. Jeg har også taget _alle_ dem jeg kunne finde, og ikke kun dem der allerede fandtes i repo'et her. `svgo` gav også en 50% reduktion.

Der er oprettet PR #21 som viser filerne. 

Jeg har ikke konverteret ikonerne (ikon.png), da opløsningen (72 dpi) simpelthen er for lille til et godt resultat. Da jeg ikke selv kan åbne EPS filerne heller, så kan jeg ikke se om de måske skulle være der som et lag - ellers mangler der en kildefil til ikonerne.. :/

**Comment by briis** [comment]
Tak Michael.
Jeg så din PR, og der jo rigtig mange SVG'er. De fleste bruger de nok på Genbrugspladsen og ikke hjemme i privaten. Jeg har kodt det ned til 26 kategorier, hvoraf jo en del er blandet i samme container, og det giver så den udfordring at vi jo ikke kan vise, eksempelvis 4 billeder, på én sensor, men der har jeg så selv lavet en ny svg med de 2-4 kategorier. Kategorierne er her:

```python
NAME_LIST = {
    "dagrenovation": "Dagrenovation",
    "farligtaffald": "Farligt affald",
    "farligtaffaldmiljoboks": "Farligt affald & Miljøboks",
    "flis": "Flis",
    "genbrug": "Genbrug",
    "glas": "Glas",
    "glasplast": "Glas, Plast & Madkartoner",
    "haveaffald": "Haveaffald",
    "jern": "Jern",
    "metalglas": "Metal & Glas",
    "pap": "Pap",
    "papir": "Papir",
    "papirglas": "Papir, Pap & Glas",
    "papirmetal": "Papir & Metal",
    "pappapir": "Pap & Papir",
    "pappapirglasmetal": "Pap, Papir, Glas & Metal",
    "pappi": "Papir & Plast",
    "plast": "Plast",
    "plastmadkarton": "Plast & Madkarton",
    "plastmetal": "Plast & Metal",
    "plastmetalmadmdk": "Plast, Metal, Mad & Drikkekartoner",
    "plastmetalpapir": "Plast, Metal & Papir",
    "restaffaldmadaffald": "Rest & Madaffald",
    "storskrald": "Storskrald",
    "storskraldogtekstilaffald": "Storskrald & Tekstilaffald",
    "tekstil": "Tekstilaffald",
}
```

**Comment by LordMike** [comment]
Lige opfølger. Har fået svaret at der ikke laves SVG’er officielt men at Illustrator filerne også kan bruges til at lave ikonerne.

Jeg formoder der er et lag i dem.

Jeg prøver om jeg kan få skabt ikon-SVG’er for alle de her filer.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by LordMike** [comment]
Så jeg fik jo ikke noget godt svar, men har så fundet ud af at kunne fjerne bogstaver fra originalerne, så vi nu har "icon" varianter. Jeg har opdateret PR'en med en SVG, en icon.SVG, og så minified udgaver af alle (fordi why not)..

Jeg har opdateret _nogle_ af billederne i `affalddk` med de her SVG'er. Min første samlede udgave er [`glasplast.svg`](https://github.com/briis/affalddk/pull/21/files#diff-d7945747d90d306e5dec286163c458399aa9984d1ea09f7ca5482643cf79a68d). Meld gerne tilbage om det er godt - for så kan jeg i Inkscape lave resten også.

**Comment by LordMike** [comment]
Så blev jeg færdig. I min branch er `affalddk/` billederne (inkl. de nyeste) lavet så de er udelukkende SVG'er. De er kvadratiske og ser rimeligt gode ud, og fylder næsten intet - den største er 5367 B (`plastmetalmadmdk`, minified). Som datauri er den 7182 B.

Jeg har ikke committet minified udgaver, jeg tænker at det kan bygges automatisk med `svgo` i en build pipeline eller hvor nødvendigt.

**Comment by briis** [comment]
Hej Michael,
Super godt. Din PR er stadig i Draft mode, så jeg har ikke merged den endnu. Jeg har lavet en fil `images.py` hvor jeg netop vil lave mapping mellem kategorierne og data:image, og så er det blot den fil der skal vedligeholdes hvis der skal ske ændringer. 
Jeg er ved at flytte Wrapperen til netop [pyaffalddk](https://github.com/briis/pyaffalddk) og det ville være fedt hvis du kunne opdatere filen `pyaffalddk/images.py` med base64/datauri ud for hver kategori.

**Comment by briis** [comment]
God pointe. `pyaffalddk` returnerer allerede en kategori, så mapningen er simpel nok. Man kunne tage `images.py` filen fra `pyaffalddk` og flytte den til HA integrationen i stedet.

**Comment by LordMike** [comment]
Kan du give mig en template for en py fil jeg kan fylde ud?

**Comment by briis** [comment]
Nedenfor finder du `images.py` filen. Det er List, hvor `data:image/svg....` så blot skal tilføjes mellem de 2 "" efter hver kategori. 

```python
"""This module contains the embedded images for Entity Pictures."""
from __future__ import annotations

PICTURE_ITEMS = {
    "batterier": "",
    "elektronik": "",
    "dagrenovation": "",
    "farligtaffald": "",
    "farligtaffaldmiljoboks": "",
    "flis": "",
    "genbrug": "",
    "glas": "",
    "glasplast": "",
    "haveaffald": "",
    "jern": "",
    "metalglas": "",
    "pap": "",
    "papir": "",
    "papirglas": "",
    "papirglasdaaser": "",
    "papirglasmetalplast": "",
    "papirmetal": "",
    "pappapir": "",
    "pappapirglasmetal": "",
    "pappi": "",
    "plast": "",
    "plastmadkarton": "",
    "plastmetal": "",
    "plastmetalmadmdk": "",
    "plastmetalpapir": "",
    "restaffaldmadaffald": "",
    "storskrald": "",
    "storskraldogtekstilaffald": "",
    "tekstil": "",
}
```

**Comment by LordMike** [comment]
Jeg bikser lige noget sammen.

**Comment by LordMike** [comment]
Prøv at tjekke det ud. Der er en bash fil der kan producere images.py, ud fra images.py.template.

**Comment by LordMike** [comment]
Har fjernet draft, da jeg tror det er klart. Images.py skal nok være et andet sted, men det ved du bedst :)

**Comment by briis** [comment]
Er på vej ud af døren til Påskefrokost, men glæder mig til at teste det hele når jeg er tilbage, senere i dag eller i morgen tidlig.

**Comment by briis** [comment]
Konen var længe om det, så jeg nåede lige at få merged dine ændringer.
Så løb jeg ind i problemer med base64 converteren. Jeg kører på en Mac, og den version virker ikke med -w flag. Havde dog lige en debian på min proxmox server jeg kunne lægge svgo ind på, og fik testet at lave images .py. Det virker perfekt, men kræver lige lidt kopiering frem og tilbage, men det overlever jeg. Stærkt arbejde Michael. Jeg har også lavet ændringen i selve programmet, så den nu bruger embedded images fra images.py.

Nu lader jeg det lige stå, og sikrer mig alt spiller, så kan jeg slippe denne udgave. Tusind tak foreløbig Michael.
