### ISSUE TITLE
Rudersdal mangler plast/papir

### ISSUE THREAD

**Issue by MisterOlsen** [briis/affalddk#15]
### Describe the issue

Tak for at Rudersdal kom med....
 Men jeg mangler at kunne se hvornår plast/papir bliver tømt.

### What version of Home Assistant Core has the issue?

2024.3.0

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

no need

**Comment by briis** [comment]
Har du et vejnavn og en by? Så tjekker jeg det lige.
Jeg synes jeg havde gået det igennem, men når jeg gør det så vælger jeg bare en tilfældig adresse eller to i kommunen

**Comment by MisterOlsen** [comment]
> Har du et vejnavn og en by? Så tjekker jeg det lige. Jeg synes jeg havde gået det igennem, men når jeg gør det så vælger jeg bare en tilfældig adresse eller to i kommunen

Stakkeledet 21, 2970

**Comment by briis** [comment]
Det er nu fixet og kommer i næste version.

**Comment by MisterOlsen** [comment]
Det lyder super, tusind tak :)

**Comment by briis** [comment]
2.0.2 er ude nu og den indeholder fix til dette.
