### ISSUE TITLE
Type mangler i Svendborg

### ISSUE THREAD

**Issue by victordk** [briis/affalddk#151]
### Describe the issue

Plastaffald mangler.

### What version of Home Assistant Core has the issue?

core-2024.9.2

### What type of installation are you running?

Home Assistant OS

### What version of the integration are you using?

2.1.16

### Diagnostics information

Material type [Plastaffald henteordning (1 stk.)] is not defined in the system for Genbrug. Please notify the developer. Municipality: Svendborg, Address ID: 13622

**Comment by briis** [comment]
Det er nu fixet i modulet. Jeg venter lige et par dage og ser om der er flere udestående, så kommer der en ny version.
