### ISSUE TITLE
Aarhus Municipalities

### ISSUE THREAD

**Issue by storebatfar** [briis/affalddk#156]
### Describe the feature you wish to make a request for

Aarhus Municipalities is a member of affald.dk please add support for Aarhus

**Comment by bravoet** [comment]
Ja det ville godt nok være dejligt - hvis Aarhus kunne komme med!

**Comment by briis** [comment]
Jeg kigger lige nu på hvordan Aarhus kan blive integreret. Tror jeg har fundet en måde at få data ud på.
Stay tuned...

**Comment by storebatfar** [comment]
@briis Fantastisk!
Jeg får testet og melder tilbage.

**Comment by storebatfar** [comment]
@briis Det ser ud til at virke helt perfekt!
Tusind tak for dette.
