### ISSUE TITLE
Bornholm

### ISSUE THREAD

**Issue by been65** [briis/affalddk#159]
### Describe the issue

Hi
Bornholm is missing a lot of fragmentations f.ex. after implementing new sorting pr. 1. october 2024.
State for next pickup also not correct at the moment.

### What version of Home Assistant Core has the issue?

2024.9

### What was the last working version of Home Assistant Core?

2024.9

### What type of installation are you running?

Home Assistant OS

### What version of the integration are you using?

2.1.17

### Diagnostics information

_

### Anything in the logs that might be useful for us?

```txt
_
```

### Additional information

_

**Comment by briis** [comment]
Jeg har brug for mere data for at kunne afhjælpe dette. Meget gerne det du ser i logfilen, og de afvigelser du ser i forhold til rapporteringen og datoer. De sidste hænger nok primært sammen med det første.
Altid svært hvis de pludselig omdøber det hele.

**Comment by Krolykke** [comment]
Samme problem for mig, kigger lige med her og ser om jeg kan bidrage med noget.

**Comment by briis** [comment]
Kig i logfilerne og se om der er noget der vedrører affalddk. Så kopier det og post det her.

**Comment by sanded001** [comment]
Får også fejl. Bornholm er jo kun lige kommet med på sortering her pr 1 oktober. så der vil komme ændringer løbende formentlig. :) se log filerne med fejl her -> 

Garbage type [Rest + plast/MDK] is not defined in the system. Please notify the developer. Municipality: Bornholm, Address ID: 43242
Garbage type [Madaffald] is not defined in the system. Please notify the developer. Municipality: Bornholm, Address ID: 43242
Garbage type [Papir/pap og glas/metal] is not defined in the system. Please notify the developer. Municipality: Bornholm, Address ID: 43242

**Comment by briis** [comment]
Tak for logfilerne. Så er der lidt at starte med. I sender bare i kraft med at der opstår nye. Jeg retter ovenstående.
Ser gerne Logilerne fra de 2 andre også, for at se om I får de samme felt, eller det er andre mangler.

**Comment by been65** [comment]
Ja kigger man i "Mit affald" app
240 l rest + plast/MDK -  (torsdag lige uger, næste 3. oktober)
140 l mad - (torsdag ulige uger, næste 10. oktober)
240 l papir/pap + glas/metal - (torsdag B-uge, næste 10. oktober, 7. november, 5. december)

**Comment by briis** [comment]
Denne her `rest + plast/MDK ` er en ny kombination, så jeg skal lige have lavet et nyt billede også.

**Comment by briis** [comment]
Kunne mindst en af jer give mig en adresse at teste på. Tingene er lavet men jeg synes ikke rigtigt jeg kan finde en adresse der giver de nye container typer. Har prøvet en vej i Rønne, Nexø og Hasle, men alle kommer med andre data og ingen fejl.
Forstår godt I ønsker den står her, så send mig evt. en email på bjarne@briis.com med adressen.

**Comment by briis** [comment]
Så har jeg frigivet version 2.1.18. Denne ser ud til at løse udfordringerne for Bornholm. Den burde selv dukke op i HACS, men ellers kan du gå ind i HACS, vælge 'Affaldshåndtering DK' og så klikke på de 3 lodrette prikker i højre hjørne, og så klikke på 'Opdateringsoplysninger'. Så burde den komme frem med det samme når du går tilbage til HACS.

Jeg lader dette issue være åben nogle dage for at sikre det virker for alle, og der ikke mangler noget.

**Comment by Krolykke** [comment]
Ser (næsten) fint ud her, tak :-) Men Billedet for pap, papir, glas og metal indikerer madaffald, pap, papir og metal.

![Skærmbillede 2024-10-06 090727](https://github.com/user-attachments/assets/797ad8e0-200e-4e56-9e68-b9f88dea26e8)

**Comment by briis** [comment]
Det er korrekt. Gad vide hvor længe den har gjort det 😀
Jeg får det rettet så det kommer med næste gang jeg laver en opdatering.
