### ISSUE TITLE
Manglende affaldstyper i Høje Taastrup.

### ISSUE THREAD

**Issue by leonkdk** [briis/affalddk#16]
### Describe the issue

Jeg mangler følgende kategorier for Høje Taastrup:
Pap
Papir/Fødevarekartoner & Plast
Glas/Metal

### What version of Home Assistant Core has the issue?

core-2024.3.0

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

None

**Comment by briis** [comment]
2.0.2 re lige posted til HACS. Den skulle gerne fixe dette.

**Comment by leonkdk** [comment]
2.0.2 installeret og problem fixet - tak for hjælpen :-)

**Comment by allanedk** [comment]
@briis Tak for det gode arbejde med denne integration!

Hvidovre mangler også nogle kategorier. Jeg har lige opdateret til 2.0.2, men de mangler stadig. 
(Skal jeg oprette et nyt Github-issue på det?)

**Comment by briis** [comment]
Nej. Bare skriv din adresse her (Eller på min email: bjarne@briis.com) og hvad du mangler, så fixer jeg det.

**Comment by dykandDK** [comment]
Jeg mangler også i Greve kommune.

Jeg har sendt en mail med adresse og flere oplysninger 😊
