### ISSUE TITLE
[FR]: Assens by

### ISSUE THREAD

**Issue by Ftw1980** [briis/affalddk#166]
### Describe the feature you wish to make a request for

Is it possible to add Assens to this list?

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by briis** [comment]
Jeg har ikke umiddelbart kunne finde et api der leverer de data. Man kan søge på en adresse og få næste tømning, men for en komplet liste viser den en kalender som en PDF og den kan jeg ikke gøre noget ved i mit program.
Hvis du en APP eller lignende så kan det være der er noget der kan gøres men altså ikke umiddelbart noget jeg kan finde.

**Comment by Ftw1980** [comment]
Der findes en app som hedder "Assens forsyningen"
De er en del af affald. Dk
![SmartSelect_20241022_150641_AffaldsGuide](https://github.com/user-attachments/assets/b032d2d6-f291-4815-a1d5-cac4b8dd13c1)
 
Kan det bruges? 🙂

**Comment by briis** [comment]
Beklager. Men nu har jeg kigget igen ifb. med nogle nye funktioner. Og jeg har ganske enkelt ikke adgang til nogen former for API der kan levere data for Assens. Det er stadig muligt det findes et sted, men ikke noget jeg kan finde ud fra det jeg kan se på deres officielle websider. Så jeg må lukke denne nu, og skulle der dukke nyt op, så er du velkommen til at åbne den igen.

**Comment by Ftw1980** [comment]
Hej briis

Tak for forsøget. 
Jeg er ikke super stærk i, hvad du endeligt efterspørger. 
Dette er deres hjemmeside: 
https://www.assensforsyning.dk/affald/hvornaar-toemmes-beholderne

Hvor tømningerne også vises. 

Igen tak for din tid👍🏻

**Comment by briis** [comment]
Ja der har jeg været inde, og jeg har tracet hvilke data de tilgår, men desværre er det de viser på siden kun den næste tømningsdato og så har du mulighed for at åbne en fuld kalender i PDF.
Det jeg gerne ville have mulighed for, var at få data i 'rå' format, så jeg kan formetere dem på en måde så de kan bruges i HA, og det kan jeg ikke finde.
Det er muligt at hvis man brugte et produkt som Wireshark eller lignende sammen med den APP du har på din mobil, at den så får data på en måde man kan bruge og at Wireshark kan sniffe de adresser den tilgår, men det vil kræve en der er god til at sætte det op - og det er ikke mig.

**Comment by newbenji** [comment]
> Hej briis
> 
> Tak for forsøget. Jeg er ikke super stærk i, hvad du endeligt efterspørger. Dette er deres hjemmeside: https://www.assensforsyning.dk/affald/hvornaar-toemmes-beholderne
> 
> Hvor tømningerne også vises.
> 
> Igen tak for din tid👍🏻

FTW hvorfor prøver du ikke skrive til dem og hører om de har mulighed for at api, eller calender feed?
