### ISSUE TITLE
næste afhentning - frekvens for opdatering?

### ISSUE THREAD

**Issue by Symbiot78** [briis/affalddk#17]
### Describe the issue

hej briis

hvor ofte opdaterer sensorerne?

næste afhentning ser pt. således ud for mig. Vi fik hentet rest i går. billedet er fra i dag.

![image](https://github.com/briis/affalddk/assets/3314249/65afe114-f2e2-41aa-ad92-54f87669afb3)

### What version of Home Assistant Core has the issue?

core-2024.2.5

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

nothing

**Comment by briis** [comment]
Den burde opdatere hver 6. time som standard. Du kan selv skrue på opdateringsfrekvensen ved gå til *Indstillinger* | *Enheder & thenester* og så klikke på integration. Her klikker du så på `KONFIGURÈR`.

Sidste den er opdateret er i går kl 22:54 og derfor står der 0. Men hvis du lige har opdateret, så burde den genopfriske data?

Er der noget i logfilen?

**Comment by Symbiot78** [comment]
jeg lavede opdateringen i går ... efter 16.. fik bare ikke kigget ift. den anden sensor.
kigger lige log.

**Comment by Symbiot78** [comment]
prøvede lige at reloade integrationen. så opdaterede den antal dage.

**Comment by briis** [comment]
Ok. Hold lige øje med om den opdaterer selv, det gør den hos mig, og det burde den også gøre hos dig.

**Comment by briis** [comment]
Antager den opdaterer korrekt, så jeg lukker dette issue. Hvis det ikke er korrekt, så genåbner du bare.
