### ISSUE TITLE
[FR]: Posible to add Fredericia

### ISSUE THREAD

**Issue by pspe612** [briis/affalddk#173]
### Describe the feature you wish to make a request for

Lækkert hvis Fredericia kommune kunne komme med på listen
det er Marius Pedersen der henter rest affaldet

**Comment by briis** [comment]
Hej igen,
I forbindelse med at jeg har lavet ændringer i mit program så jeg nu kan understøtte nogle kommuner der ikke bruger Renoweb, har jeg kigget på Fredericia igen. Kommunen bruger et firma der hedder 'Affald.dk' (Det gør en del andre kommuner også) og de leverer ikke data i et data format, men KUN som et website. Og den eneste måde man så kan få data på, at man tager det html kode der laves og søger efter bestemte tekster på siden for så at få nogle data ud. (Web Scraping). Der skal kun rettes en enkelt stavefejl på siden, så kan jeg risikere at skulle opdatere programmet igen, så jeg har valgt ikke at kaste mig over kommuner der ikke leverer data som data.
Beklager meget, men jeg lukker denne nu.

Jeg har lavet en funktion der gør det muligt at hente data fra en iCalendar fil, så skulle kommunen på et tidspunkt tilbyde I kan abonnere på en sådan en, så åben gerne en ny request.
