### ISSUE TITLE
[BUG] [Genbrugsspand, 240L (2-delt) (1 stk.)] is not defined

### ISSUE THREAD

**Issue by Strit** [briis/affalddk#186]
### Describe the issue

I get this in my error log:

```
Denne fejl stammer fra en brugerdefineret integration.

Logger: pyaffalddk.api
Kilde: custom_components/affalddk/__init__.py:123
integration: Affaldshåndtering DK (dokumentation, problemer)
Første forekomst: 24. november 2024 kl. 23.40.24 (2 forekomster)
Senest logget: 03.40.24

Material type [Genbrugsspand, 240L (2-delt) (1 stk.)] is not defined in the system for Genbrug. Please notify the developer. Municipality: Esbjerg, Address ID: 74775
```

I assume it's because the bins have been renamed on the api side.

### What version of Home Assistant Core has the issue?

2024.11.3

### What type of installation are you running?

Home Assistant Container

### What version of the integration are you using?

2.1.19

### Diagnostics information

[home-assistant_affalddk_2024-11-25T06-37-58.456Z.log](https://github.com/user-attachments/files/17898423/home-assistant_affalddk_2024-11-25T06-37-58.456Z.log)

### Anything in the logs that might be useful for us?

```txt
2024-11-25 07:37:39.207 WARNING (MainThread) [pyaffalddk.api] Material type [Genbrugsspand, 240L (2-delt) (1 stk.)] is not defined in the system for Genbrug. Please notify the developer. Municipality: Esbjerg, Address ID: 74775
2024-11-25 07:37:39.208 DEBUG (MainThread) [custom_components.affalddk] Data fetched 2024-11-25 07:37:39
2024-11-25 07:37:39.208 DEBUG (MainThread) [custom_components.affalddk] Finished fetching affalddk data in 0.201 seconds (success: True)
```

### Additional information

There has been some changes to which bins we have in the last couple of months here in Esbjerg, so this might just be an API endpoint that has been renamed or changed in some other way.

**Comment by briis** [comment]
Hejsa,
Jeg skal nok fixe det, men det er lidt svært at se ud fra beskrivelsen hvad der skulle være i den container `Genbrugsspand, 240L (2-delt) (1 stk.)`. Er det mad og restaffald, eller?

**Comment by briis** [comment]
Tak. Jeg har fixet det, men arbejder lige nu på en lidt større opdatering, så der går lige nogle dage før næste version kommer ud, men her er det med.

**Comment by Strit** [comment]
Lækkert, tak for det. :smile:
