### ISSUE TITLE
affaldstyper for kerteminde  mangler

### ISSUE THREAD

**Issue by koburg** [briis/affalddk#19]
### Describe the issue

Der mangler affaldstyper det var der i den gamle renoweb for kerteminde.

<img width="342" alt="image" src="https://github.com/briis/affalddk/assets/3473374/54f5009c-d241-4ae2-a0ee-0e338df194c6">

tror det er den der hedder plast der mangler.

den skriver også en fejl/advarsel i loggen 

### What version of Home Assistant Core has the issue?

2024.3.0

### What was the last working version of Home Assistant Core?

2024.3.0

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

n/a

### Anything in the logs that might be useful for us?

```txt
Denne fejl stammer fra en brugerdefineret integration.

Logger: pyrenoweb.api
Kilde: custom_components/affalddk/__init__.py:116
integration: Affaldshåndtering DK (dokumentation, problemer)
Første forekomst: 10.31.55 (4 forekomster)
Senest logget: 10.42.14

Material type [Gen-Skel 0-2 meter (1 stk.)] is not defined in the system for Genbrug. Please notify the developer
Material type [240 l genbrug 2-kammer (2023) (1 stk.)] is not defined in the system for Genbrug. Please notify the developer
```

### Additional information

n/a

**Comment by briis** [comment]
Dem skal jeg nok få tilføjet. Tak
Og det du ser i loggen er helt med vilje, det gør det hurtigere for mig at tilføje det der mangler

**Comment by koburg** [comment]
> Dem skal jeg nok få tilføjet. Tak Og det du ser i loggen er helt med vilje, det gør det hurtigere for mig at tilføje det der mangler

Tak!
Smart måde at gøre det på 👍🏻😀 med log.

**Comment by briis** [comment]
De er nu lagt på. 
Jeg er i tvivl hvad denne `Gen-Skel 0-2 meter (1 stk.)` indeholder, så jeg har lagt den i den generiske Genbrugskategori. Kan det være haveaffald?

**Comment by koburg** [comment]
ja det kunne det godt være for den har vi fysisk ikke fået endnu men kommer vist nok på et tidspunkt.

**Comment by briis** [comment]
Så ligger jeg den i Haveaffald. Hvis det viser sig at være forkert, må du sige til.

**Comment by koburg** [comment]
nu er det dagen før der skal hentes rest og mad affald samt plastic.

<img width="338" alt="image" src="https://github.com/briis/affalddk/assets/3473374/fea26ff4-48d7-4d62-a7de-e7a8c703113a">

men som billede viser er der ikke nogen plast. 

den gamle sensor hed : sensor.renoweb_plast_skel_0_2_meter 
den viser dog en som er utilgængelig men den har  ikke ændret sig længe. har haft genstartet.
