### ISSUE TITLE
Flere affaldstyper virker ikke i Egedal Kommune

### ISSUE THREAD

**Issue by philipheyde** [briis/affalddk#194]
### Describe the issue

Når jeg konfigurerer integrationen til min adresse i Egedal Kommune kommer følgende fejl i HA-loggen. De nævne affaldstyper oprettes ikke hos mig. Jeg får stadig oprettet disse:

- Genbrug
- Haveaffald
- Rest- & madaffald

`This error originated from a custom integration.

Logger: pyaffalddk.api
Source: custom_components/affalddk/__init__.py:130
integration: Affaldshåndtering DK (documentation, issues)
First occurred: 5:38:40 PM (4 occurrences)
Last logged: 5:38:40 PM

Material type [370 l Plast+MDK/Papir - Egenløsning (Privat) (1 stk.)] is not defined in the system for Genbrug. Please notify the developer. Municipality: Egedal, Address ID: 26395
Material type [240 l Pap Egenløsning (Privat) (1 stk.)] is not defined in the system for Genbrug. Please notify the developer. Municipality: Egedal, Address ID: 26395
Material type [240 l Glas/metal Egenløsning (Privat) (1 stk.)] is not defined in the system for Genbrug. Please notify the developer. Municipality: Egedal, Address ID: 26395
Garbage type [Juletræ] is not defined in the system. Please notify the developer. Municipality: Egedal, Address ID: 26395`

### What version of Home Assistant Core has the issue?

core-2024.11.2

### What type of installation are you running?

Home Assistant Container

### What version of the integration are you using?

2.2.0

### Diagnostics information

[home-assistant_affalddk_2024-12-02T16-47-54.434Z.log](https://github.com/user-attachments/files/17981209/home-assistant_affalddk_2024-12-02T16-47-54.434Z.log)

**Comment by briis** [comment]
Hej,
Dette sker desværre typisk omkring årskiftet hvor kommunerne pludselig vil lave om på teksterne i deres containere. Jeg får det løst og sender en opdatering ud.

**Comment by philipheyde** [comment]
Super. Tak for hurtigt svar. Jeg hjælper gerne med at teste, når/hvis der er behov for det.

**Comment by briis** [comment]
Hej,
Hent den sidste nye version, hvor du gerne skulle se alle dine affaldstyper.

**Comment by philipheyde** [comment]
Tak. Jeg har allerede opgraderet, og det ser ud til at virke helt efter planen. Dejligt!
