### ISSUE TITLE
[FR] Ønske om sortering - Først kommende afhentning øverst

### ISSUE THREAD

**Issue by HrCalmar** [briis/affalddk#198]
### Describe the feature you wish to make a request for

Først og fremmest tak for en awesome integration!

Vi herhjemme har dog ønske om at afhentningerne kunne blive sorteret.

Således den først kommende afhentning står øverst.

**Comment by briis** [comment]
Hej Simon,
Det kunne jeg godt lave, men personligt bruger jeg det kort der hedder `auto-entities` som du kan downloade fra [HACS](https://github.com/thomasloven/lovelace-auto-entities) Her kan du sortere dine entities præcis på den måde du vil have det. Prøv evt. at kigge på det først.

**Comment by HrCalmar** [comment]
Kære @briis 

`Auto-entities` var ny for mig, og det virkede perfekt :-)

![image](https://github.com/user-attachments/assets/d47d28ba-a771-4971-a009-951f2512c7ba)

**Comment by briis** [comment]
Perfekt. Ja det kort er faktisk ganske fantastisk.
