### ISSUE TITLE
[FR]: Frederikshavn

### ISSUE THREAD

**Issue by cbjerg** [briis/affalddk#29]
### Describe the feature you wish to make a request for

Kunne Frederikshavn komme med? De bruger en side der hedder https://renovation.forsyningen.dk/minside/Tomningsinfo?siteType=R til at søge efter data, og den er ikke gemt bag noget login.

**Comment by briis** [comment]
Det ser ud til at det bagved liggende API er det samme som Affald Thy bruger. (Se #31) Som jeg skriver der, så et hurtigt kig på deres API, så ser det ud til der er en måde at få data ud på, men jeg kan ikke love noget før jeg har brugt lidt mere tid.
Men jeg kigger på det.

**Comment by briis** [comment]
Jeg har nu brugt lidt tid på at kigge Frederikshavn Kommunes website igennem, for at se om jeg på nogen måde kunne hente data ud. Men de tilbyder desværre ikke data i nogen former for API, som jeg kan tilgå offentligt. Data er udelukkende præsenteret som en tabel på websiden, og det vil betyde man skal bruge Webscraping for at få dem ud i et brugbart format. Webscraping er ikke noget jeg ønsker at bruge her, da det er alt for usikkert om man får de rigtige data og det kræver alt for megen vedligeholdelse, da kommunen jo kan ændre layout på websiden i morgen, og så skal man starte forfra.

Jeg må desværre lukke denne, og Frederikshavn vil ikke bliver understøttet i denne Integration. Beklager.
