### ISSUE TITLE
næste afhentning er negativ

### ISSUE THREAD

**Issue by ruteclrp** [briis/affalddk#30]
### Describe the issue

![image](https://github.com/briis/affalddk/assets/115367766/7bb2b058-037f-4bd1-bf72-4f211de948ca)
virkede fint for første afhentning i går. Næste afhentning er om en dag, men bliver vist negativ??

### What version of Home Assistant Core has the issue?

core-2024.3.0

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

n.a.

### Anything in the logs that might be useful for us?

```txt
n.a.
```

### Additional information

n.a

**Comment by ruteclrp** [comment]
kiggede i calenderen. afhentningen af papir&Plast i går er ikke mere at finde i kalenderen. Næste papir& plast er 9/4.
ser ud som om at "næste afhentning ikke hopper til  - næste afhentning!

**Comment by ruteclrp** [comment]
Så er den gal igen

![image](https://github.com/briis/affalddk/assets/115367766/6ccba951-f528-40e0-bdff-96f1a59464af)

Går i negativ for dage til næst afhentning. Kalenderen er renset for afhentningen i går. 

Genstart af HA løser problemet. Men, det er vel ikke meningen?

**Comment by ruteclrp** [comment]
Også gal efter afhentning af Pap i går. Nu står næste afhentning på -1 dag. Ser ud til at der en generel fejl med at resette tæller efter afhentning. Genstart af HA løser problemet midlertidigt.

**Comment by rhgiter** [comment]
min næste afhentning , håndterere kun 1  spand - og der er 2 der tømmes samme dag
(hillerød)

**Comment by briis** [comment]
> min næste afhentning , håndterere kun 1 spand - og der er 2 der tømmes samme dag (hillerød)

Se #42

**Comment by briis** [comment]
Med hensyn til -1 dag, så har jeg selv set fejlen hos mig. Den arbejdes der på.
