### ISSUE TITLE
[FR]: Thisted municipality

### ISSUE THREAD

**Issue by bossybum** [briis/affalddk#31]
### Describe the feature you wish to make a request for

Could you maybe add the municipality for Thisted

**Comment by briis** [comment]
Thisted bruger ikke Renoweb og derfor er der ikke en Quick Fix. Jeg har lige kort kigget på Affald Thy (Eller Thy Recycling) og uden jeg kan love noget, så kan jeg måske trække data ud fra det de stiller til rådighed. 
Kan ikke love noget, men jeg vil kigge på det når jeg lige er bund med de andre ting.

**Comment by briis** [comment]
Jeg har nu brugt lidt tid på at kigge Thisted Kommunes website igennem, for at se om jeg på nogen måde kunne hente data ud. Men de tilbyder desværre ikke data i nogen former for API, som jeg kan tilgå offentligt. Data er udelukkende præsenteret som en tabel på websiden, og det vil betyde man skal bruge Webscraping for at få dem ud i et brugbart format. Webscraping er ikke noget jeg ønsker at bruge her, da det er alt for usikkert om man får de rigtige data og det kræver alt for megen vedligeholdelse, da kommunen jo kan ændre layout på websiden i morgen, og så skal man starte forfra.

Jeg må desværre lukke denne, og Thisted vil ikke bliver understøttet i denne Integration. Beklager.
