### ISSUE TITLE
Manglende entiteter og forkert dato

### ISSUE THREAD

**Issue by JanHG** [briis/affalddk#32]
### Describe the issue

Efter skiftet fra RenoWeb integrationen mangler jeg nu entiteter for (alle med samme afhentningsdag):
- Papir/glas/dåser
- Plast
- Batterier

'Farligt affald & Miljøboks' er sat til afhentningsdagen for ovenstående, hvilket ikke er den korrekte afhentningsdag for 'Farligt affald & Miljøboks'.

Jeg bor i 2680 Solrød Strand.

### What version of Home Assistant Core has the issue?

core-2024.3.1

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[home-assistant_affalddk_2024-03-15T15-57-49.642Z.log](https://github.com/briis/affalddk/files/14617889/home-assistant_affalddk_2024-03-15T15-57-49.642Z.log)

**Comment by briis** [comment]
Ja, det kan jeg se. De har dog godt valgt en helt anden navngivnings syntaks i Solrød, end stort set alle andre kommuner. Jeg er i gang med at kigge på det.

**Comment by JanHG** [comment]
> Ja, det kan jeg se. De har dog godt valgt en helt anden navngivnings syntaks i Solrød, end stort set alle andre kommuner. Jeg er i gang med at kigge på det.

Ok, tak. Lad mig høre hvis jeg kan hjælpe.
