### ISSUE TITLE
Getting error invalid message handler

### ISSUE THREAD

**Issue by vaibhavratnaparkhi** [briis/affalddk#33]
### Describe the issue

<img width="398" alt="image" src="https://github.com/briis/affalddk/assets/149868727/757a8bd2-c225-43e1-8bba-6ab436b32be2">

Getting error invalid message handler

### What version of Home Assistant Core has the issue?

core-2024.3.0

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

Getting error invalid message handler

**Comment by briis** [comment]
Forventer det er samme fejl som #4 Prøv lige at tjekke om det der står der ikke hjælper dig.

**Comment by briis** [comment]
Ingen aktivitet. Sagen lukkes. Hvis det mod forventning ikke er løst, så åben den igen.

**Comment by vaibhavratnaparkhi** [comment]
Works fine now. #4 resolution was helpful
