### ISSUE TITLE
[FR]: Kalender begivendenheder som heldags begivenhed

### ISSUE THREAD

**Issue by kgn3400** [briis/affalddk#34]
### Describe the feature you wish to make a request for

Hej, 
Har du mulighed for at indsætte begivenheder i kalenderen som heldags begivenheder i stedet for fra 00.00 til 00.00?  Eller lave en options til enten eller? 

Jeg bruger dette Lovelace kort hassio-trash-card( https://github.com/idaho/hassio-trash-card). Og den opfører sig ikke helt pænt når kalender begivenhederne ikke heldags begivenheder 😕

Mvh
Kurt G. Nielsen

**Comment by briis** [comment]
Hej,
Ja det tror jeg godt jeg kan. Jeg er i gang med rettelser, så jeg ser om jeg ikke kan få dette ændret.
