### ISSUE TITLE
Missing material type

### ISSUE THREAD

**Issue by chrjoedal** [briis/affalddk#35]
### Describe the issue

Hi,

I am living in Svenstrup J (Aalborg), and is getting this warning in the log, which states you would like to know it :)

This error originated from a custom integration.  Logger: pyrenoweb.api Source: custom_components/affalddk/__init__.py:116 integration: Affaldshåndtering DK (documentation, issues) First occurred: 11:17:51 PM (2 occurrences) Last logged: 11:17:51 PM  Material type [240L genbrug (1 stk.)] is not defined in the system for Genbrug. Please notify the developer

Thank you for your work!

### What version of Home Assistant Core has the issue?

core-2024.3.0

### What type of installation are you running?

Home Assistant Container

### Diagnostics information

None

**Comment by briis** [comment]
Tak. Kan du sige hvad der er i denne container? Det er nemlig ikke lige til at gætte ud fra beskrivelsen

**Comment by chrjoedal** [comment]
Selvfølgelig.
Det er en todelt container, med Pap/Papir i det ene rum, og plastik, mademballage og metal i det andet rum.

**Comment by briis** [comment]
Den optræder 2 gange med samme indhold og data, men jeg opretter kun én sensor. Åben dette issue igen hvis det ikke stemmer. Men det er fixet nu.
