### ISSUE TITLE
Config flow could not be loaded: {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by Symbiot78** [briis/affalddk#4]
### Describe the issue

after install trying to add to HA and while it's starting the config I get this error

Config flow could not be loaded: {"message":"Invalid handler specified"}

### What version of Home Assistant Core has the issue?

core-2024.2.5

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

I don't get that far.

### Anything in the logs that might be useful for us?

```txt
Error occurred loading flow for integration affalddk: cannot import name 'GarbageCollection' from 'pyrenoweb' (/usr/local/lib/python3.12/site-packages/pyrenoweb/__init__.py)
```

**Comment by briis** [comment]
Renoweb og denne integration kan ikke sameksistere, så følgende fra README er vigtigt:

1. First remove Renoweb from the Devices & Services section.
2. Then go to HACS, and de-install Renoweb
3. Finally restart Home Assistant

Så Renoweb skal fjernes helt og Home Assistant skal genstartes, så kan du prøve igen.

**Comment by Symbiot78** [comment]
Thanks
I had not rebooted my HA after removing the old integration
