### ISSUE TITLE
Lyngby Taarbæk: Mangler "4-kammer beholder"

### ISSUE THREAD

**Issue by macsatcom** [briis/affalddk#40]
### Describe the issue

Der mangler den beholder der har sorteret affald (papir, glas, metal og plast). 
De andre beholdere er der som de skal være og dagene ser rigtige ud.

Det virkede i forrige version ("RenoWeb")

### What version of Home Assistant Core has the issue?

2024.3.1

### What was the last working version of Home Assistant Core?

None

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

no tech issue as such

**Comment by briis** [comment]
Tak. Fejlen er fundet og det kommer med i næste release.

**Comment by macsatcom** [comment]
Jeg har opgraderet til seneste, genstartet HA og endda prøvet at reloade integrationen. Jeg mangler stadig 4-kammer-beholder.
