### ISSUE TITLE
2 afhentninger samme dag

### ISSUE THREAD

**Issue by rhgiter** [briis/affalddk#41]
### Describe the issue

min næste afhentning , håndterere kun 1 spand - og der er 2 der tømmes samme dag
(hillerød)

### What version of Home Assistant Core has the issue?

-

### What was the last working version of Home Assistant Core?

-

### What type of installation are you running?

Home Assistant Core

### Diagnostics information

-

### Anything in the logs that might be useful for us?

```txt
-
```

### Additional information

-

**Comment by briis** [comment]
Hej,
Jeg antager, men du må korrigere hvis det er forkert, at den sensor der hedder næste afhentning, kun viser den en af de 2 tømninger du har den dag? Er det korrekt? Kan du se begge containere som separate sensorer med den samme dato?

Hvis ja, er det ikke en direkte fejl, men en feature der ikke er implementeret. Næste afhentning vil altid kun indeholde en sensor.

Hvordan så du det gerne?

**Comment by briis** [comment]
Hvis ovenstående er korrekt, er det samme som #42. Følg med der for opdatering.
