### ISSUE TITLE
Wrong dates reported by affalddk for address in Rebild

### ISSUE THREAD

**Issue by bregendahlen** [briis/affalddk#44]
### Describe the issue

Don't know if this has to do with the fact, that Nordværk has taken over the garbage service in Rebild recently, and that this service is reporting data from the old portal. From the data it shows that the data was delivered by renoweb? affalddk reports that my trash will be picked up tomorrow, but it won't be until the 26th of march - so some data is not right.

### What version of Home Assistant Core has the issue?

core-2024.3.1

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

none

**Comment by bregendahlen** [comment]
Jeg tror måske de er gået fra renoweb og over til dette: https://www.affaldonline.dk/kalender/rebild/

**Comment by briis** [comment]
Det er korrekt. Jeg får nedenstående besked når jeg prøvet at tilgå data. Så rebild er desværre ikke understøttet pt. 
Der er en del Nordjyske kommuner der ser ud til at skifte til en anden leverandør af data, og jeg kigger på det i nærmeste fremtid, om jeg kan få dem med ind. Ingen løfter dog.

![Skærmbillede 2024-03-22 kl  07 46 10](https://github.com/briis/affalddk/assets/24776272/c040ce48-915f-470d-a324-84d85a43d64c)

**Comment by briis** [comment]
Jeg har nu brugt lidt tid på at kigge Rebild Kommunes website igennem, for at se om jeg på nogen måde kunne hente data ud. Men de tilbyder desværre ikke data i nogen former for API, som jeg kan tilgå offentligt. Data er udelukkende præsenteret som en tabel på websiden, og det vil betyde man skal bruge Webscraping for at få dem ud i et brugbart format. Webscraping er ikke noget jeg ønsker at bruge her, da det er alt for usikkert om man får de rigtige data og det kræver alt for megen vedligeholdelse, da kommunen jo kan ændre layout på websiden i morgen, og så skal man starte forfra.

Jeg må desværre lukke denne, og Rebild vil ikke bliver understøttet i denne Integration. Beklager.
