### ISSUE TITLE
Tekstiler ikke mappet korrekt i Roskilde

### ISSUE THREAD

**Issue by briis** [briis/affalddk#49]
### Describe the issue

C´Kategorien tekstiler bliver lagt i Farligt Affald eller Genbrug. Den skal klasificeres som tekstilaffald.

### What version of Home Assistant Core has the issue?

core-2024.3.2

### What was the last working version of Home Assistant Core?

core-2024.3.2

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

None

### Anything in the logs that might be useful for us?

```txt
None
```

### Additional information

None

**Comment by Symbiot78** [comment]
noget lignende her - vi har slet ikke tekstil afhentning her i Aalborg området. - se billede

![image](https://github.com/briis/affalddk/assets/3314249/e05653d2-9446-4bf8-848a-eb8512d88a3f)

![image](https://github.com/briis/affalddk/assets/3314249/8aa6597f-1df2-4266-a511-5117b971c3cf)

**Comment by briis** [comment]
Jeg kan ikke huske om du har sendt mig din adresse tidligere, men inden jeg lige slipper den næste release, kan du så ikke sende mig din adresse på email bjarne@briis.com, så tjekker jeg lige alt er mappet korrekt.
