### ISSUE TITLE
Forkert afhentnings dato

### ISSUE THREAD

**Issue by michaeltryl** [briis/affalddk#5]
### Describe the issue

Jeg er i Randers Kommune
I min sensor.affalddk_*********_rest_madaffald sensor står der at jeg får hentet den 15-03-2024, men det bliver hentet den 13-03-2024
og min 
sensor.affalddk_*********_genbrug står der den 21-03-2024, men det bliver hentet den 11-03-2024

De datoer er taget fra vores affalds app, som plejer at passe

### What version of Home Assistant Core has the issue?

core-2024.2.5

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[home-assistant_affalddk_2024-03-06T10-00-06.540Z.log](https://github.com/briis/affalddk/files/14507974/home-assistant_affalddk_2024-03-06T10-00-06.540Z.log)

**Comment by briis** [comment]
Jeg kigger på det.

**Comment by briis** [comment]
Vil du dele din adresse? Hvis ikke her, kunne du sende mig den på email: bjarne@briis.com.
Grunden til jeg spørger er at jeg tror det skyldes der må være flere veje i kommunen der har det samme navn som den vej du bor på, og det giver et problem i mit system, da den kun viser den første den finder.  Jeg vil godt lige have bekræftet dette.

Jeg arbejder på en løsning på det problem.

**Comment by michaeltryl** [comment]
Det er et godt bud. jeg har sendt en mail med min adresse :-)

**Comment by briis** [comment]
Hej Michael,
Det var præcis problemet. Der findes også en Svinget 2 i Randers by, og det var den du fik data for. Jeg har nu lavet en ændring, så man skal indtaste sit postnummer sammen med adressen, så sikrer vi den rammer rigtig. Så når jeg har sluppet den næste version, så gå til *Indstillinger* og *Enheder & tjenester*, find *Affaldshåndtering DK* og klik på den. Ud for den adresse der ligger nu, klik på de tre vertikale prikker og sig *Fjern*. Nu er den forkerte adresse væk, og du kan tilføje en ny, hvor du bliver bedt om at indtaste dit post nummer. 

Jeg har fået et par andre indrapporteringer som jeg lige kigger på, men forventer at slippe en ny version i løbet af weekenden senest.

**Comment by michaeltryl** [comment]
Det er hurtig ekspedition :)
God dag. Jeg kigger på det til næste version.

Hilsen
Michael Baadsgaard
***@***.***
22269362
www.magiske-michael.dk


Har du bestilt et trylleshow - kan du læse betingelserne her:

https://magiske-michael.dk/betingelser/

Hvis du liker min Facebook side, vil du få gode tilbud, info om hvor jeg
optræder, konkurrencer osv.
https://www.facebook.com/magiske.michael/





tors. 7. mar. 2024 07.15 skrev Bjarne Riis ***@***.***>:
