### ISSUE TITLE
Lyngby-Taarbæk - stadig manglende 4-kammer-beholder :)

### ISSUE THREAD

**Issue by macsatcom** [briis/affalddk#50]
### Describe the issue

Jeg har opdateret til v. 2.05 - ,men mangler desværre stadig 4-kammer beholder. Selv efter genstart af HA og reload af integration.

![image](https://github.com/briis/affalddk/assets/55062853/489ea060-32ab-4de1-9be5-97473d781ad5)

### What version of Home Assistant Core has the issue?

n/a

### What was the last working version of Home Assistant Core?

n/a

### What type of installation are you running?

Home Assistant Container

### Diagnostics information

![image](https://github.com/briis/affalddk/assets/55062853/d23239e4-1b65-40a7-b3e9-eb9f374879fc)

**Comment by briis** [comment]
Det er altid svært at teste for samtlige adresser, og der er desværre mange kombinationer af containere og blandinger i disse. Kunne du sende mig din adresse på email bjarne@briis.com, så tester jeg specifikt på denne, og ser om jeg ikke kan løse det.
