### ISSUE TITLE
[FR]: Vestforbrændingen/Renoweb

### ISSUE THREAD

**Issue by Hjeresen** [briis/affalddk#51]
### Describe the feature you wish to make a request for

Integrationen ser rigtig fin ud (hvis jeg bruger en adresse i nabobyen), men jeg har et problem. Jeg bor i Farum (Furesø) som er på listen, men jeg får en fejl når jeg slår min adresse op (se vedhæftede skærmdump) Jeg kan få oplysninger om hentning på Vest forbrændingens hjemmeside.
![Skærmbillede 2024-03-24 173923](https://github.com/briis/affalddk/assets/34107574/a805a6b8-7cd8-4853-9f11-799c7d81d944)

Hilsen Bo

**Comment by briis** [comment]
Ja, det ser ud som om Furesø nu har droppet Renoweb og bruger vestforbrænding som data leverandør. Jeg får nedenstående besked når jeg prøver at bruge en adresse i furesø, hvilket desværre betyder at jeg må fjerne dem fra listen.
Jeg kiggede lige hurtigt om jeg kunne få nogle data i et brugbart format fra Vestforbrænding, men det ser desværre ikke sådan ud. Beklager.

<img width="734" alt="Skærmbillede 2024-03-24 kl  20 09 30" src="https://github.com/briis/affalddk/assets/24776272/26cea543-2284-408f-9891-24bba5643d68">

**Comment by Hjeresen** [comment]
Tusind tak for svar, og for at tjekke Vestforbrændingen! 
Hilsen Bo
