### ISSUE TITLE
[FR]: add Lejre Kommune 

### ISSUE THREAD

**Issue by TamerBakir** [briis/affalddk#52]
### Describe the feature you wish to make a request for

I snit possible to add Lejre Kommune?

**Comment by briis** [comment]
Just checked again, and it seems Lejre is supported. Don't know why I left them out in the first place. They will be added in the next release.

**Comment by TamerBakir** [comment]
Hej Bjarne

Det er dog ikke muligt at vælge Lejre?

Se vedhæftede fil

man. 25. mar. 2024 09.18 skrev Bjarne Riis ***@***.***>:

**Comment by briis** [comment]
Nej. Jeg skal sende en opdatering ud først. Samler lidt flere rettelser, så kommer det i morgen eller torsdag

**Comment by TamerBakir** [comment]
Helt fint. Tak for opdateringen og god aften 😊

man. 25. mar. 2024 19.44 skrev Bjarne Riis ***@***.***>:

**Comment by TamerBakir** [comment]
Hej Bjarne

Jeg har fået denne besked om at den er completed, jeg kan dog fortsat ikke
finde Lejre, er det fordi den kommer i morgen ?

Beklager ulejligheden.

Den tirs. 26. mar. 2024 kl. 16.32 skrev Bjarne Riis <
***@***.***>:

**Comment by briis** [comment]
HACS er nogen gange lidt langsom. Prøv at gå ind HACS, find AffaldDK og klik på den. Gå så tilbage, og den vil sige der er en opdatering. Installer denne, genstart Home Assistant og se burde det virke.

**Comment by TamerBakir** [comment]
Hej Bjarne

Vil det være for meget for langt hvis du i din beskrivelse viser nogle
eksempler på hvordan man kan udnytte sensor og calender entry ? til de af
os som ikke er 100m mester. Lidt a la nogle andre integrationer, hvor de
kort har nogle eksempler man kan copy/paste til at lave et fint card på
dashboard.

God påske :)
vh
Tamer Bakir

Den ons. 27. mar. 2024 kl. 13.14 skrev Bjarne Riis ***@***.***

**Comment by briis** [comment]
Hej Tamer,
Nej bestemt ikke. Der er bare så mange ting man kunne vise, så hvis det er noget bestemt du har brug for, så lad mig det vide, og jeg vil gerne hjælpe dig i gang med nogle eksempler.

De bedste hilsner,

Bjarne Riis
Toftebuen 69
4000 Roskilde
Mobil: 2619 1701
E-Mail: ***@***.******@***.***>


Fra: TamerBakir ***@***.***>
Dato: torsdag, 28. marts 2024 kl. 23.34
Til: briis/affalddk ***@***.***>
Cc: Bjarne Riis ***@***.***>, State change ***@***.***>
Emne: Re: [briis/affalddk] [FR]: add Lejre Kommune (Issue #52)
Hej Bjarne

Vil det være for meget for langt hvis du i din beskrivelse viser nogle
eksempler på hvordan man kan udnytte sensor og calender entry ? til de af
os som ikke er 100m mester. Lidt a la nogle andre integrationer, hvor de
kort har nogle eksempler man kan copy/paste til at lave et fint card på
dashboard.

God påske :)
vh
Tamer Bakir

Den ons. 27. mar. 2024 kl. 13.14 skrev Bjarne Riis ***@***.***

**Comment by TamerBakir** [comment]
De nye piktogrammer også fine 😊

Jeg har lige fået hentet skrald i går og synes at den ser lidt underlig ud.

Se vedhæftet billede



søn. 31. mar. 2024 09.41 skrev Bjarne Riis ***@***.***>:

**Comment by briis** [comment]
Hej Tamer,
Du glemte at vedhæfte billedet.

De bedste hilsner,

Bjarne Riis
Toftebuen 69
4000 Roskilde
Mobil: 2619 1701
E-Mail: ***@***.******@***.***>


Fra: TamerBakir ***@***.***>
Dato: onsdag, 3. april 2024 kl. 19.01
Til: briis/affalddk ***@***.***>
Cc: Bjarne Riis ***@***.***>, State change ***@***.***>
Emne: Re: [briis/affalddk] [FR]: add Lejre Kommune (Issue #52)
De nye piktogrammer også fine 😊

Jeg har lige fået hentet skrald i går og synes at den ser lidt underlig ud.

Se vedhæftet billede



søn. 31. mar. 2024 09.41 skrev Bjarne Riis ***@***.***>:

**Comment by TamerBakir** [comment]
Det blev rettet i seneste opdatering

Beklager ulejligheden og tak for et godt stykke arbejde :)

Vh
Tamer Bakir

tors. 4. apr. 2024 07.05 skrev Bjarne Riis ***@***.***>:
