### ISSUE TITLE
forkert billede på entiteten 'næste afhentning'

### ISSUE THREAD

**Issue by ruteclrp** [briis/affalddk#57]
### Describe the issue

![image](https://github.com/briis/affalddk/assets/115367766/935e7a36-d047-4177-aab4-bed256fca4d4)
![image](https://github.com/briis/affalddk/assets/115367766/59ab58ed-6bb7-4a81-8ab8-4e2b9875fc49)

Har opdateret til sidste nye version og downloaded billeder zip-fil.

### What version of Home Assistant Core has the issue?

core-2024.3.3

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

Diag not available

### Additional information

De første verseioner var OK, men denne fejl har været der i de sidste par versioner.

Og, så er afhentning i øvrigt i dag og ikke i morgen - som rapporteret på den anden bug.

**Comment by briis** [comment]
Se #54. Fejlen er rettet og kommer med i næste release.
