### ISSUE TITLE
Viser kun "genbrug" på adressen

### ISSUE THREAD

**Issue by Bredum** [briis/affalddk#59]
### Describe the issue

Hej, 

Jeg for kun "genbrug" frem, når jeg taster min adresse. Jeg har sendt dig en mail med min adresse. 

### What version of Home Assistant Core has the issue?

core-2024.3.3

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

2024-03-26 10:17:09.003 WARNING (MainThread) [pyrenoweb.api] Material type [Pap og papir/metal, glas og hård plast - 240 L (1 stk.)] is not defined in the system for Genbrug. Please notify the developer

**Comment by briis** [comment]
Tak for input og adressen.
Jeg får to containere frem på adressen. Den ene (Pap og papir/metal, glas og hård plast) har jeg nu lagt korrekt, men din Dagrenovation kan jeg ikke rigtig gøre noget ved lige nu, da det eneste data jeg får er Onsdag i ulige uger - den skriver helt konkret: Ingen tømningsdato. Når jeg får det sidste, så er standard at jeg ignorerer containeren, da jeg jo ikke kan fortælle hvornår den bliver afhentet.

For at jeg kan få den med, så skal jeg lave en funktion der 'oversætter' "Onsdag i ulige uger" til noget systemet ved er en onsdag og en ulig uge, og derefter finde ud hvordan jeg så kan beregne hvornår det er og få en rigtig dato retur. Det er ikke så ligetil. Så det er ikke noget der kommer lige nu.

**Comment by briis** [comment]
Denne lukkes med næste opdatering, og så må jeg se om jeg senere kan finde en metode at hente dato, når der reelt ikke er nogen.
