### ISSUE TITLE
wrong types of garbage types in Egedal

### ISSUE THREAD

**Issue by ruteclrp** [briis/affalddk#6]
### Describe the issue

My integration loads these types:
`  - calendar.affalddk_skovhavevej_2
  - entity: sensor.affalddk_skovhavevej_2_farligt_affald
    name: Farligt affald
  - entity: sensor.affalddk_skovhavevej_2_genbrug
    name: Genbrug
  - entity: sensor.affalddk_skovhavevej_2_haveaffald
    name: Haveaffald
  - entity: sensor.affalddk_skovhavevej_2_naeste_afhentning
    name: Næste afhentning
  - entity: sensor.affalddk_skovhavevej_2_rest_madaffald
    name: Rest- & madaffald
  - entity: sensor.affalddk_skovhavevej_2_storskrald
    name: Storskrald`

My app from the municipality gives these types:
Farligt Affald
240 l Glas/metal
Haveaffald
Juletræ
240 l Pap
370 l Plast+MDK/Papir
240 L Rest/Mad
Storskrald

### What version of Home Assistant Core has the issue?

 core-2024.2.5

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

No log available at this time

### Anything in the logs that might be useful for us?

```txt
Nothing so far
```

**Comment by briis** [comment]
Hvilken kommune taler vi om? Så undersøger jeg det lige.

**Comment by ruteclrp** [comment]
Som overskriften siger - Egedal :-)

**Comment by briis** [comment]
Undskyld, det så jeg ikke lige 😅
Jeg har fået en besked fra en anden bruger i Egedal, og har nu fundet ud hvorfor det ikke virker helt som det skal i Egedal, og muligvis også enkelte andre steder. Der er et felt i de data jeg får retur der hedder `ordningsnavn`. Det felt bliver brugt til at adskille containerne i de forskellige typer. Problemet i Egedal er at de bruger ordet Genbrug på 3 container, og man skal så ned i nogle andre felter for at adskille dem. Det er nu lavet, og kommer med i næste version.

Nu den er ude, og du har testet, må du gerne give mig besked.

**Comment by jesperll** [comment]
Fedt. Skulle ellers lige til at rapportere samme problem i Allerød.
Pap, plast/papir og glas/metal er også alle under samme ordningsnavn "genbrug"

**Comment by jesperll** [comment]
@briis med release 2.0.2 ser jeg nu pap som selvstændig sensor, men glas/metal hedder stadig bare "genbrug" og  plast/papir mangler helt. Allerød Kommune. 

Plast/papir, afstand over 5 meter (1 stk.)
Glas/metal, afstand over 5 meter (1 stk.)

**Comment by briis** [comment]
Ja beklager. Jeg måtte lave Genbrugs containerne mere generisk, da det optræder i flere kommuner. I den proces tabte jeg lige Egedal. Beklager. 

Jeg sender en fix ud i morgen.

**Comment by briis** [comment]
Så er de 2 Genbrugs containere du har listet ovenfor lagt ind.
Og mht. juletræ, så er det korrekt, at alle containere der ikke har en dato, ikke bliver vist, da hele konceptet er bygget på at jeg kan beregne hvor mange dage der er til næste afhentning.
