### ISSUE TITLE
Fokert datovisning

### ISSUE THREAD

**Issue by chrjoedal** [briis/affalddk#60]
### Describe the issue

Vi skulle have hentet Papir & plast idag, 26/3.
Attributten "Date sort" for den sensor viser helt korrekt: "Tir d. 26/03", men desværre viser "Duration": "I morgen" og couteren for sensoren viser 1 i stedet for 0, selvom afhentningen var i dag.

Jeg ville have forventet at "Duration" ville skrive "I dag", og sensorens couteren var 0 i stedet for 1.

Se bilede:
![image](https://github.com/briis/affalddk/assets/8665515/3d7bb5b8-59d6-48a1-b2fc-ab1d233be942)

### What version of Home Assistant Core has the issue?

core-2024.3.0

### What type of installation are you running?

Home Assistant Container

### Diagnostics information

Could  not download it

### Anything in the logs that might be useful for us?

```txt
Living in Svenstrup J, Aalborg.
```

**Comment by briis** [comment]
Det er fixet. Prøv at opdatere til 2.0.7 og se om det ikke har løst problemet.

**Comment by hmsjel** [comment]
Yes det virker nu

**Comment by chrjoedal** [comment]
Det virker, beklager dublet issue

**Comment by briis** [comment]
No problem. Jeg lukker sagen.
