### ISSUE TITLE
"Genbrug" vises forkert på adressen

### ISSUE THREAD

**Issue by frankebobdk** [briis/affalddk#67]
### Describe the issue

Hej,

Først og fremmest vil jeg gerne takke dig for den indsats, du lægger i denne udvidelse!

Jeg har bemærket, at på min adresse og generelt for Mariagerfjord Kommune, vises "Genbrug" ikke korrekt som den affaldsbeholder, den faktisk er. 
For at præcisere, så dækker genbrugsaffaldet faktisk over "papir/pap/metal/plast/mad- og drikkekartoner".

Kan du _(såfremt muligt)_ ændre det, så "Genbrug" vises som "papirglasmetalplast.svg"? 
Jeg mener, at dette vil være den mest retvisende angivelse.

### What version of Home Assistant Core has the issue?

core-2024.4.0

### What type of installation are you running?

Home Assistant OS

### What version of the integration are you using?

2.1.1

### Diagnostics information

Material type [240 l genbrug låg i låg (1 stk.)] is not defined in the system for Genbrug. Please notify the developer.

**Comment by briis** [comment]
Det kan jeg sagtens. Jeg har lige testet med en adresse i Hobro, og her var der ganske rigtigt en container der hed `240 l genbrug låg i låg (1 stk.)`. Men for at være helt sikker på det er samme container hos dig, kunne du sende mig din adresse på bjarne@briis.com, så tester jeg lige at det virker. Ved du allerede at den hedder det samme, så er alt OK, og den er lagt i `papir/pap/metal/plast/mad- og drikkekartoner` og du behøver ikke sende noget.

**Comment by frankebobdk** [comment]
Adresse sendt på mail og tak for hjælpen 👍

**Comment by frankebobdk** [comment]
Ved ikke om det skal noteres her, men næste afhentning viser stadig det gamle genbrug logo, og er ikke opdateret. 

Har prøvet at reloade adressen, men viser stadig det gamle logo.

**Comment by briis** [comment]
Er det efter du har opdateret til 2.1.3?
Den er lige frigivet for et par timer siden

**Comment by frankebobdk** [comment]
Ja har netop opdaget for cirka 20 min siden. 

Se nedenstående billede

![image](https://github.com/briis/affalddk/assets/50303454/0eb3111f-f6f2-4c2a-8b90-dda67fe90724)

**Comment by briis** [comment]
Bare for at være helt sikker: og du har genstartet Home Assistent?

**Comment by frankebobdk** [comment]
> Bare for at være helt sikker: og du har genstartet Home Assistent?

Ja har genstartet Home Assistant - 2 gange endda for at være sikker.

**Comment by briis** [comment]
Godt, så må jeg lige hvorfor det ikke virker. Beklager

**Comment by briis** [comment]
Det er sgu underligt. Jeg har lige lagt din adresse ind på en test udgave af Home Assistant, med V2.1.3 installeret. og den viser det helt som den skal: 

![Skærmbillede 2024-04-07 kl  15 54 05](https://github.com/briis/affalddk/assets/24776272/f2a45288-b97a-4998-890b-1d41d0fc9e39)

Når jeg kigger nærmere på dit billede, så er logoet jo korrekt, det er kun teksten der vises forkert. Gad vide om det er et cache problem med browseren? Eller har du selv skrevet teksten?

**Comment by frankebobdk** [comment]
Tror vi snakker forbi hinanden 😊 

Jeg mener logoet på entiteten "naeste afhentning". Burde den ikke have opdateret logoet til det korrekte?

**Comment by briis** [comment]
Ja 😀 vi snakker forbi hinanden.
Nej det Logo er altid det samme. Grunden til det, er at der nogen, der får hentet flere containere på én dag, og så samler jeg teksten og beskrivelsen fra alle containere. Men det vil så bliver umuligt at lave alle logoer for de containere, da sammensætningen kan være rigtig mange forskellige. Derfor er næste afhentning altid et Genbrugs logo. 

Denne ændring kom i V2.0.5 Se release notes her https://github.com/briis/affalddk/blob/main/CHANGELOG.md#version-205

**Comment by frankebobdk** [comment]
Beklager, det havde jeg ikke set 😊 
Så virker alt som det skal. 
Du må gerne lukke dette issue.

Tak for hjælpen.
