### ISSUE TITLE
[FR]: Mangler Bornholm 

### ISSUE THREAD

**Issue by micv83** [briis/affalddk#7]
### Describe the feature you wish to make a request for

Kan Bornholm blive tilføjet. Kommune nummer 400. 

https://bofa.renoweb.dk/Legacy/selvbetjening/mit_affald.aspx

Virkede med den gamle Renoweb integration.

**Comment by briis** [comment]
Jeg tjekkede bornholm, og de så ikke ud til at levere de data jeg skal bruge, men jeg tjekker det igen. Det bliver først i løbet af weekenden. Bare behold den gamle Renoweb integration, indtil jeg melder klar.

**Comment by briis** [comment]
Hvis man skal søge tømningsdata på Bornholm så skal man ind på et system drevet af Fugato. De bruger så noget der linker til dette: http://tomningskalender.dk/skrald/calendar.asp og det understøtter jeg ikke lige nu. Jeg vil kigge på om jeg kan hive data ud af dette også.
Som sagt, så længe Renoweb integrationen virker så brug den, jeg fjerner den ikke fra nettet.

**Comment by briis** [comment]
Jeg har nu brugt lidt på at kigge på det system Bornholm bruger til affaldsdata, og det er desværre ikke muligt at udtrække data herfra, som jeg har kunnet se. Beklager.

**Comment by briis** [comment]
Hejsa,
Jeg frigiver snart den næste version og har lavet en opdatering som burde understøtte Bornholm også. Jeg mangler dog test data, så lav et nyt issue hvis alt ikke kommer med.
Husk at inkludere data fra din Log fil, da der her står det jeg skal bruge for at fejlsøge.
