### ISSUE TITLE
Vesthimmerland

### ISSUE THREAD

**Issue by rbusk88** [briis/affalddk#70]
### Describe the feature you wish to make a request for

Er det muligt at tilføje Vesthimmerlands kommune/ Vesthimmerlands forsyning?
https://renomatic.renovest.dk/MinSide/Tomningsinfo?AdresseId=9539&siteType=R&kom=0&lang=dk

På forhånd tak.
Vh. Rasmus

**Comment by briis** [comment]
Desværre nej. Jeg har tjekket kommunen tidligere og har lieg gjort det igen med det link du sendte, og de leverer desværre ikke data i et format som kan trækkes ind her. De andre leverer data som et datasæt, man så kan finde de informationer man skal bruge, men her bliver det lagt ind som html og den eneste måde jeg kan få data ud, er at gå hver enkelt linje igennem og se om jeg kan finde et mønster i hvor de skriver det data vi skal bruge. Det er ikke en metode jeg vil kaste mig ud i, da det er næsten umuligt at få til at virke for alle adresser, og samtidig, hvis selskabet laver om i deres layout, så starter man forfra.

Så beklager meget, men indtil der findes en måde hvor vi kan få de rå data, så kan jeg ikke supportere kommunen.
