### ISSUE TITLE
[FR]: Faxe Kommune

### ISSUE THREAD

**Issue by ScarFaceDK** [briis/affalddk#71]
### Describe the feature you wish to make a request for

Er det muligt at få Glas/Jern oprettet også? 
Samt at genbrug er  Plast/Pap. Evt. en rettelse? 

Ellers spiller det perfekt ;)

**Comment by briis** [comment]
Det kan jeg helt sikkert. Kunne du sende mig fin adresse på bjarne@briis.com så sikrer det jeg får det hele med.

**Comment by ScarFaceDK** [comment]
Adresse sendt ;)

**Comment by briis** [comment]
Tak. Og modtaget. Jeg får kigget på det snarest.

**Comment by briis** [comment]
Så er det fixet. Kommer med i næste version. Afventer lige et par dage for at se om der er flere.

**Comment by ScarFaceDK** [comment]
Perfekt, Glæder mig 😉

Med venlig hilsen / Best regards / Mit freundlichen Grüßen

Morten Hansen


Mobil: +45 2027 4248 - Telefon +45 4369 2600 - Geminivej 29-31 - 2670 Greve DK
CVR nr. 15554347 - Email ***@***.*** - Web www.brdr-autodele.dk <http://www.brdr-autodele.dk/>

***@***.***
***@***.***


Fra: Bjarne Riis ***@***.***>
Sendt: 11. april 2024 07:00
Til: briis/affalddk ***@***.***>
Cc: Morten Hansen ***@***.***>; Author ***@***.***>
Emne: Re: [briis/affalddk] [FR]: Faxe Kommune (Issue #71)


Så er det fixet. Kommer med i næste version. Afventer lige et par dage for at se om der er flere.
