### ISSUE TITLE
Material type not defined

### ISSUE THREAD

**Issue by CTNielsen** [briis/affalddk#75]
### Describe the issue

Getting this warning in log
Material type [240 L todelt genbrugsspand hver 4. uge (1 stk.)] is not defined in the system for Genbrug. Please notify the developer

### What version of Home Assistant Core has the issue?

core-2024.4.3

### What was the last working version of Home Assistant Core?

core-2024.4.3

### What type of installation are you running?

Home Assistant Container

### What version of the integration are you using?

v2.1.4

### Diagnostics information

None

### Anything in the logs that might be useful for us?

```txt
Material type [240 L todelt genbrugsspand hver 4. uge (1 stk.)] is not defined in the system for Genbrug. Please notify the developer
```

**Comment by briis** [comment]
Tak for info. Hvilken kommune drejer det sig om, og hvad er der i spanden. Restaffald/Mad?

**Comment by CTNielsen** [comment]
Det er Varde kommune og skraldespanden er til plastik/kartonner i den ene side og glas/metal i den anden side

**Comment by briis** [comment]
Tak for det. Det var så en ny kombination af affald i en container 😅
Jeg skal lave have lavet et nyt billede før jeg kan tilføje den.

**Comment by CTNielsen** [comment]
![image](https://github.com/briis/affalddk/assets/25704712/1e704763-b425-4c01-9ca2-88c7ec865196)
Det ser sådan ud på deres hjemmeside

**Comment by briis** [comment]
Super. Det får jeg lavet.

**Comment by briis** [comment]
2.1.5 er lige pakket sammen og uploaded. Den dukker op i HACS snarest og ellers kør en manuel søgning i HACS.
Lukker dette issue nu.
