### ISSUE TITLE
Storskrald Odsherred opdaterer ikke

### ISSUE THREAD

**Issue by ChiliJohn** [briis/affalddk#76]
### Describe the issue

Efter sidste opdatering er storskrald forsvundet :-)
(Denne entitet leveres ikke længere af affalddk-integrationen.)

### What version of Home Assistant Core has the issue?

core-2024.4.3

### What type of installation are you running?

Home Assistant OS

### What version of the integration are you using?

Seneste

### Diagnostics information

Denne entitet leveres ikke længere af affalddk-integrationen. 
Hvis entiteten ikke længere er i brug, kan du slette den i indstillinger.
Storskrald
I forgårs
Utilgængelig

### Additional information

Første gang jeg reporterer noget her, håber det er rigtigt gjort. er ellers super glad for integrationen. Godt arbejde!

**Comment by briis** [comment]
Tak for info. Ja jeg lavede en ændring som kunne give dette resultat. Hvis du sender mig din adresse på 
bjarne@briis.com så ser jeg lige hvorfor det ikke virker.

**Comment by hmsjel** [comment]
Jeg har fået samme issus, (Randers kommune)

**Comment by briis** [comment]
Jeg ruller noget af ændringen tilbage for at sikre det virkede som før. Kommer med i næste release.

**Comment by briis** [comment]
Version 2.1.6 er lige blevet posted. Den skulle gerne fixe problemet for jer begge.
