### ISSUE TITLE
Glostrup kommune "Standpladser"

### ISSUE THREAD

**Issue by MagnusKlink** [briis/affalddk#79]
### Describe the issue

Integrationen viser kun storskrald, haveaffald og næste afhentning - ikke sådan noget som pap, plast, madaffald etc. 

### What version of Home Assistant Core has the issue?

core-2024.4.4

### What type of installation are you running?

Home Assistant OS

### What version of the integration are you using?

v2.1.6

### Diagnostics information

[home-assistant_affalddk_2024-04-24T17-05-09.382Z.log](https://github.com/briis/affalddk/files/15097897/home-assistant_affalddk_2024-04-24T17-05-09.382Z.log)

### Anything in the logs that might be useful for us?

```txt
This error originated from a custom integration.

Logger: pyaffalddk.api
Source: custom_components/affalddk/__init__.py:123
integration: Affaldshåndtering DK (documentation, issues)
First occurred: 18:58:00 (7 occurrences)
Last logged: 18:58:00

Garbage type [Standpladser] is not defined in the system. Please notify the developer. Municipality: Glostrup, Address ID: 2361
```

**Comment by briis** [comment]
Tak for rapporten. Hvor mange fysiske containere mangler du data for? Det nemmeste ville være hvis du kunne sende mig din adresse på email: bjarne@briis.com, så kan jeg de rå data der kommer.

**Comment by briis** [comment]
OK, jeg kan se hvad udfordringen. Jeg får lavet en fix snarest.
