### ISSUE TITLE
[FR]: Tilføj Rudersdal kommune

### ISSUE THREAD

**Issue by bomorville** [briis/affalddk#8]
### Describe the feature you wish to make a request for

Kan Rudersdal kommune tilføjes? 

https://rudersdal.renoweb.dk/Legacy/selvbetjening/mit_affald.aspx

Det virkede i Renoweb integrationen

**Comment by briis** [comment]
Jeg tjekker lige igen hvorfor jeg ikke tog dem med. Det bliver nok weekend før jeg når til det, indtil da bare behold den gamle Renoweb integration.

**Comment by briis** [comment]
Så fik jeg lidt tid. Jeg var alle 98 kommuner igennem, og Rudersdal virker faktisk, så det må være en smutter den røg ud.
Jeg har lagt den tilbage, og det kommer med i næste version.

Hvis det virker for dig når næste version er ude, så luk dette issue.
