### ISSUE TITLE
affalddk_adresse_naeste_afhentning | statisk billede?

### ISSUE THREAD

**Issue by Symbiot78** [briis/affalddk#80]
### Describe the issue

nok mest et spørgsmål.
jeg bruger denne sensor: affalddk_adresse_naeste_afhentning i et button card til at vise næste afhentning.
Burde den skifte ikon alt efter, hvad der bliver afhentet? eller er ikonet til den sensor statisk?

hos mig viser den altid denne

![image](https://github.com/briis/affalddk/assets/3314249/e1205c99-29f1-47f0-b400-fffc7457458b)

### What version of Home Assistant Core has the issue?

core-2024*

### What was the last working version of Home Assistant Core?

ingen

### What type of installation are you running?

Home Assistant OS

### What version of the integration are you using?

2.1.6

### Diagnostics information

*

**Comment by briis** [comment]
Denne specifikke sensor indeholder oplysninger om alle de Containere der bliver hentet næste gang. Hos rigtig mange, kan det være mere end en container og derfor er det umuligt at afgøre hvilket icon der skal bruges. Så ikonet er statisk med det du viser ovenfor per design.
