### ISSUE TITLE
Material type/definition is not defined in the system for Genbrug

### ISSUE THREAD

**Issue by PTRSC** [briis/affalddk#83]
### Describe the issue

This error originated from a custom integration.

Logger: pyaffalddk.api
Source: custom_components/affalddk/__init__.py:123
integration: Affaldshåndtering DK (documentation, issues)
First occurred: April 28, 2024 at 16:55:21 (138 occurrences)
Last logged: 08:55:26

Material type [Papir, 660 liter (3 stk.)] is not defined in the system for Genbrug. Please notify the developer. Municipality: Lyngby-taarbæk, Address ID: 55180
Material type [Plast, 660 liter (2 stk.)] is not defined in the system for Genbrug. Please notify the developer. Municipality: Lyngby-taarbæk, Address ID: 55180
Material type [Metal, 660 liter (1 stk.)] is not defined in the system for Genbrug. Please notify the developer. Municipality: Lyngby-taarbæk, Address ID: 55180
Material type [Glas, 660 liter (2 stk.)] is not defined in the system for Genbrug. Please notify the developer. Municipality: Lyngby-taarbæk, Address ID: 55180
Material type [Pap, 660 liter (3 stk.)] is not defined in the system for Genbrug. Please notify the developer. Municipality: Lyngby-taarbæk, Address ID: 55180

### What version of Home Assistant Core has the issue?

core-2024.4.4

### What type of installation are you running?

Home Assistant OS

### What version of the integration are you using?

v2.1.6

### Diagnostics information

See "Describe the issue" field

**Comment by briis** [comment]
Jeg fixer det i weekenden
