### ISSUE TITLE
Material type is not defined in the system

### ISSUE THREAD

**Issue by hmsjel** [briis/affalddk#87]
### Describe the issue

Jeg får dette i min log:
Ved ikke om det er fordi at Randers kommune er ved at udskifte affalds beholdere, da vi skal have mere sotering
Logger: pyaffalddk.api
Source: custom_components/affalddk/__init__.py:123
integration: Affaldshåndtering DK (documentation, issues)
First occurred: 12:44:53 (3 occurrences)
Last logged: 12:44:53

Material type [240L papir, pap (1 stk.)] is not defined in the system for Genbrug. Please notify the developer. Municipality: Randers, Address ID: 77468
Material type [240L plast, MDK/metal, glas gl. (1 stk.)] is not defined in the system for Genbrug. Please notify the developer. Municipality: Randers, Address ID: 77468
Garbage type [Beholderudbringning] is not defined in the system. Please notify the developer. Municipality: Randers, Address ID: 77468

### What version of Home Assistant Core has the issue?

2024.5.2

### What was the last working version of Home Assistant Core?

2024.5.2

### What type of installation are you running?

Home Assistant OS

### What version of the integration are you using?

nyeste version

### Diagnostics information

ingen

**Comment by briis** [comment]
Tak. Jeg har fixet dem alle. Dog kan jeg ikke gennemskue hvad denne beholder `[Beholderudbringning]` dækker over. Jeg har lige nu lagt den som Genbrug, da jeg ikke umiddelbart har en kategori den passer ind i. Ved du hvad det er?

**Comment by hmsjel** [comment]
Hej
Tak for det
Jeg tror at beholderudbringig dækker over hvilken dag vi måske får en ekstra beholder. 

Med venlig hilsen
Tommy Johannesen
Sendt fra min iPhone 🙂

**Comment by briis** [comment]
OK. Jeg tager den ud. Hvis du mangler den senere, så åben en ny sag.

**Comment by hmsjel** [comment]
1000 tak, nu virker det som det skal igen :-)
