### ISSUE TITLE
[FR]: Show next pickup for "all" types of recycling

### ISSUE THREAD

**Issue by Symbiot78** [briis/affalddk#9]
### Describe the feature you wish to make a request for

in the old component I could see when the next everyday-rubbish pickup was and also the next recycling (plastic, cardboard/paper etc) it seems the new cannot?
If I understand it correctly the integration will dynamicall change between the different pickup types.
The calendar sensor just shows "off".
The 2 sensors for pickup (next and type) are 100% identical in the content they show. Won't they always be?
Is this correct?
Is it possible to see the next for more than 1 type of pickup?

**Comment by briis** [comment]
The concept has not changed from the Renoweb integration.

In the Renoweb integration you have a sensor containing `next_pickup`, this sensor was always equal to the next container that was being picked up, so you would find a similar sensor in your system with the same data.

In this integration you have a sensor, which sensor name ends with `_naeste_afhentning`, again this sensor is dynamic and will always show you the next container thats being picked up. Personally I use this on my dashboard to always show how many days until the next pickup, like below:

![Skærmbillede 2024-03-07 kl  07 34 50](https://github.com/briis/affalddk/assets/24776272/3cfa6700-617d-4501-b7bd-13889f4a1a9e)

Does this answer the first part of your question?

>> Is it possible to see the next for more than 1 type of pickup?

I guess it is, just not sure how you want this presented? Can you give me an example on how you would use it? 
If you use [this Custom Card](https://github.com/thomasloven/lovelace-auto-entities) you could sort all your sensors, and display them in ascending order, to show the pickups. (You can even exclude the Næste Afhentning sensor to not show it twice).

P.S. Du må gerne skrive på dansk 😀

**Comment by Symbiot78** [comment]
hej Bjarne

Jeg har desværre ikke lige et billede fra før opdatering, men jeg brugte følgende:

`  - type: "custom:button-card"
    color_type: card
    icon: mdi:delete
    name: Affald
    size: 140px
    custom_fields:      
      recycle: >
        [[[ return (states['sensor.renoweb_190l_med_14_dagstomning'].state)  ]]]

      metals: > 
        [[[ return (states['sensor.renoweb_240l_genbrug'].state)  ]]]
`

egentligt "bare" et buttoncard med 2 små indikatorer der viste x dage til næste, og 2 forskellige farver.

dette er det tætteste billede jeg lige kan give dig.. her er kun 1 indikator, men ideen er den samme.

![image](https://github.com/briis/affalddk/assets/3314249/23e6645c-5b95-4132-b14f-7649b6a1ca1a)

jeg har kigget alle sensorerne, og jeg kan ikke finde et sted, hvor jeg kan se data på både rest og plast (det er lige de 2 afhentninger vi har her i aalborg kommune.) Begge kunne jeg se som ovenstående kode.

**Comment by Symbiot78** [comment]
nå... suk... 
data er der nu, efter opdatering - hvor ny sensor er kommet med for aalborg... haha...

vi lukker denne

**Comment by briis** [comment]
OK nu tror jeg jeg forstår hvad du er efter. Du burde dog have en sensor for hver af disse typer. Jeg testede med en helt tilfældig adresse på Strøybergs Minde og fik begge de 2 containere frem. Hvis du kunne skrive din adresse (evt. bare på email bjarne@briis.com) så vil jeg lige undersøge det nærmere.

Intentionen er at du for hver container hvor jeg finde en dato, opretter en sensor som i den tidligere integration, og den kan du så bruge som du plejede.

**Comment by briis** [comment]
Vi postede lige samtidig 😀
Godt det virker nu. Mangler du en container, så skriv bare igen.
