### ISSUE TITLE
wrong dates provided

### ISSUE THREAD

**Issue by SenfMeister78** [briis/affalddk#92]
### Describe the issue

Storskrald is picked up in less than a month. yet the intgrations says 134 days. (since day one its been asy in the future.  
(I live in Gladsaxe)

### What version of Home Assistant Core has the issue?

 	core-2024.5.3

### What type of installation are you running?

Home Assistant OS

### What version of the integration are you using?

2.0.4

### Diagnostics information

.

**Comment by briis** [comment]
Kunne du prøve at opdatere til den seneste version (2.1.8) og se om det løser dit problem.

**Comment by SenfMeister78** [comment]
Hej Bjarne.

Har lige været udenlands ,så jeg har ikke fået kigget endnu. Er i toget på
vej mod lufthavnen.  :)
Hvis jeg opdaterer i Home Assistant, bør det så ikke være nyeste udgave?

Den tirs. 21. maj 2024 kl. 08.46 skrev Bjarne Riis ***@***.***

**Comment by briis** [comment]
Jo det burde det, men du skriver V2.0.4 i din Bug Report, derfor spørger jeg. Tjek lige når du er på systemet igen.
Jeg spørger også fordi den fejl du oplever blev fixet efter 2.0.4 så derfor ligner det en manglende opdatering fra HACS.

**Comment by SenfMeister78** [comment]
Tak.
Jeg kigger lige når jeg har ramt hjemmet og får 10 minutter :)

Den fre. 24. maj 2024 kl. 10.27 skrev Bjarne Riis ***@***.***

**Comment by SenfMeister78** [comment]
Det kører..  Tusinde tak for hjælpen :)

Den tirs. 28. maj 2024 kl. 09.13 skrev Anders Nørklit Thingholm <
***@***.***>:
