### ISSUE TITLE
[FR]: 3 beholdere

### ISSUE THREAD

**Issue by michaeltryl** [briis/affalddk#96]
### Describe the feature you wish to make a request for

I Randers kommune er vi ved at få leveret en ekstra affaldsbeholder.
Kommer den ekstra beholder automatisk på som en sensor, når det er registreret at vi har fået vores ekstra beholder leveret, eller skal jeg gøre noget i integrationen?

**Comment by briis** [comment]
I princippet skulle de komme automatisk når integrationen opdaterer data næste gang. MEN de kan have givet de nye beholdere helt andre navne og derfor kan du risikere nogen ikke dukker op. Mangler du nogen, så tjek i loggen for Home Assistant, her vil du kunne finde nogle WARNINGS med beskrivelse af hvad den ikke kunne finde. Kopier disse linjer og post dem her, så fixer jeg det.

**Comment by michaeltryl** [comment]
Det vil jeg gøre :)

**Comment by briis** [comment]
Fik du fulgt op på denne?

**Comment by michaeltryl** [comment]
Ikke endnu. Vi får først vores nye beholdere om en uge / 14 dage :)

**Comment by michaeltryl** [comment]
Vi fik vores nye beholder i går og i dag var der oprettet nye sensorer så det virkede smertefrit

**Comment by briis** [comment]
Fedt. Jeg lukker sagen.
