### ISSUE TITLE
Type mangler for Slagelse

### ISSUE THREAD

**Issue by Toftbo** [briis/affalddk#97]
### Describe the issue

Hej og tak for integrationen

For Slagelse manger typen: [Plast, Mad- og drikkekartoner, Småt Pap og Papir]

### What version of Home Assistant Core has the issue?

core-2024.5.2

### What type of installation are you running?

Home Assistant Container

### What version of the integration are you using?

2.1.8

### Diagnostics information

Garbage type [Plast, Mad- og drikkekartoner, Småt Pap og Papir] is not defined in the system. Please notify the developer. Municipality: Slagelse, Address ID: 31131

**Comment by briis** [comment]
Tak. Denne er nu fixet. Venter lige et par dage for at se om der er flere.

**Comment by briis** [comment]
Så er 2.1.9 sendt til HACS, og den fixer dette. Jeg lukker issuet.
